name: linter and tests 

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests: 
    
        runs-on: ubuntu-latest

        steps:
            
            - uses: actions/checkout@v4
            
            - name: Install Hatch
              uses: pypa/hatch@install

            - name: Check linting
              run: hatch fmt
            
            - name: Run tests
              run: hatch test